name: CI
'on':
  push:
    branches:
      - main
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build PDF
        uses: dita-ot/dita-ot-action@master
        with:
          input: document.ditamap
          transtype: pdf
          output-path: foo
          
      - name: Upload DITA Output to a ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: dita-artifact
          path: 'foo'
          
      - name: Deploy DITA Output to branch
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: shart # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.